# 📘 NumPy / Array Learning Notes

In [4]:
import numpy as np # import numpy library

#### Basic Array Creation

In [5]:
arr = np.array([1,2,3,4,5]) # basic array creation
arr

array([1, 2, 3, 4, 5])

In [7]:
a = [1,2,3.5,4, 'hello'] # basic list creation
a

[1, 2, 3.5, 4, 'hello']

In [8]:
np.array(a) # list convert to array

array(['1', '2', '3.5', '4', 'hello'], dtype='<U32')

In [9]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l) # two dimensinal array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Array Generation Function

In [11]:
arr = np.arange(1,10) # range generation
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr = np.zeros(6) # zero generation
arr

array([0., 0., 0., 0., 0., 0.])

In [14]:
arr = np.zeros((4,8)) # 4 rows 8 columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones((6, 6)) # generation ones
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
arr = np.linspace(1,5,3) # linear space (start, end, space)
arr

array([1., 3., 5.])

#### Random Generation Function

In [22]:
arr = np.random.rand(5) # vectors and normalizations 0 to 5
arr

array([0.05349972, 0.66765082, 0.5961824 , 0.82466837, 0.24846205])

In [24]:
arr = np.random.randn(5) # vectors and standardization -5 to 5
arr

array([ 0.74540816, -0.43598477,  0.91790682,  2.08026102,  0.98545414])

In [26]:
arr = np.random.randint(5) # single random number generate
arr

1

In [35]:
arr = np.random.randint(10, 20, 5) # integer array generate (low point, high point, number of array)
arr

array([17, 19, 11, 14, 11], dtype=int32)

#### Array Attributes

In [37]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

####  Array Methods

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.sum()

np.int64(45)

In [45]:
np.sum(arr, axis=0) # o axis means colum wise for 2 dimensional

array([12, 15, 18])

In [46]:
np.sum(arr, axis=1) # 1 axis means row wise for 2 dimensional

array([ 6, 15, 24])

In [47]:
arr.mean()

np.float64(5.0)

In [48]:
arr.std() # statndard daviation

np.float64(2.581988897471611)

In [49]:
arr.argmax() # argument maximum index

np.int64(8)

In [50]:
arr.argmin() # argument minimum index

np.int64(0)

#### Reshaping and Resizing

In [56]:
arr = np.arange(1,31) # one dimensional array
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])