# 📘 NumPy / Array Indexing And Slicing Notes

In [1]:
import numpy as np

#### Indexing And Slicing Vectors

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
# Indexing Part
arr_index = arr[9]
arr_index

np.int64(20)

In [33]:
# Slicing Part
arr_slice = arr[2:]
arr_slice

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
arr_slice = arr[:10]
arr_slice

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
arr_slice = arr[2:10]
arr_slice

array([13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
arr_slice = arr[2:10:2] # slicing (start index, end index, steps)
arr_slice

array([13, 15, 17, 19])

#### Indexing And Slicing Matrix

In [24]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
# Indexing Part
arr_index = arr[5,4] # first row index then column index
arr_index

np.int64(30)

In [43]:
# slicing Part
arr_slice = arr[0:2, 1:3] # first row indexes then column indexes
arr_slice

array([[2, 3],
       [7, 8]])

In [44]:
arr_slice = arr[3:, 3:] # first row indexes then column indexes
arr_slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [45]:
arr_slice = arr[:, 2] # first row indexes then column indexes
arr_slice

array([ 3,  8, 13, 18, 23, 28])

#### Boolean Indexing

In [50]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [51]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [52]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])