# 📘 Array Operation

In [1]:
import numpy as np

#### Arithmatic Operations

In [5]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [6]:
a1+a2 # shape should be the same, otherwise shows an error

array([ 7,  9, 11, 13, 15])

In [7]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [8]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [9]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1 // a2

array([0, 0, 0, 0, 0])

In [11]:
a1 % a2

array([1, 2, 3, 4, 5])

In [12]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

#### Broadcasting

In [13]:
l = [10,20,30,40]
arr = np.array(l)

In [14]:
arr + 10 # this is called braodcasting

array([20, 30, 40, 50])

In [15]:
arr = np.arange(1, 26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
arr + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

#### Deep And Shallow Copy

In [29]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
# Shallow Copy
arr_slice = arr[:5]
arr_slice = arr_slice * 10
arr_slice

array([10, 20, 30, 40, 50])

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
arr1 = arr.copy()
arr1[0] = 10
arr1

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
arr

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
# Deep Copya
arr2 = arr
arr2[0] = 10
arr2

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
arr

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix Operations

In [40]:
mat1 = np.array([[1,2], [3,4]])
mat2 = np.array([[5,6], [7,8]])

In [41]:
mat1

array([[1, 2],
       [3, 4]])

In [42]:
mat2

array([[5, 6],
       [7, 8]])

In [43]:
mat1 * mat2

array([[ 5, 12],
       [21, 32]])

In [44]:
mat1 @ mat2 # multiplication of matrix array

array([[19, 22],
       [43, 50]])

In [45]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [46]:
mat1

array([[1, 2],
       [3, 4]])

In [47]:
mat1.T

array([[1, 3],
       [2, 4]])

# 📘 Advance Array Manupulations

#### Stacking Array

In [48]:
mat1

array([[1, 2],
       [3, 4]])

In [49]:
mat2

array([[5, 6],
       [7, 8]])

In [50]:
# In stack manipulation, only vector arrays work
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [52]:
np.vstack((a1, a2)) # vertical stack

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
np.hstack((a1, a2)) # horizontal stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
np.column_stack((a1, a2)) # column stack

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

#### Spliting Array

In [55]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
np.hsplit(c,2) # horizontal split but it needs equal division

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [57]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [58]:
np.vsplit(c,2) # vertical split but it needs equal division

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [59]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]